### ISSUE TITLE
Admit opted-in peer messages through the live turn coordinator

### ISSUE THREAD

**Issue by yogeshprasad098** [tyldra-org/falryn#1082]
## Outcome

An explicitly opted-in, live Falryn recipient can consume an authorized peer request at a safe boundary or start one visible idle continuation. Delivery, model admission, execution and reply remain separate facts. Default behavior stays notification plus explicit retrieval.

## Baseline and scope

At `62b00a0b6ca0b476b7e75182531d74c4aa43ec70`, #897 and PR #1009 deliver authenticated same-machine mailboxes, inbound policy, receipts and notices. Arrival/release starts no model turn. Extend that delivered service; keep #897 closed for its recorded local-mailbox scope. This issue owns the proposed mailbox-to-turn admission integration, including durable deduplication, live composition and focused tests. It does not own a second mailbox, scheduler, workflow engine, remote transport or cross-worktree grant.

## Source owners and dependencies

- [`src/domain/orchestration/peer-mailbox.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/domain/orchestration/peer-mailbox.ts)
- [`src/application/orchestration/peer-mailbox.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/application/orchestration/peer-mailbox.ts)
- [`src/data/orchestration/mailbox-store.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/data/orchestration/mailbox-store.ts)
- [`src/application/runtime/turn-coordinator.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/application/runtime/turn-coordinator.ts)
- [`src/application/runtime/product-live-turn.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/application/runtime/product-live-turn.ts)
- [`src/cli/runtime/product-peer-mailboxes.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/cli/runtime/product-peer-mailboxes.ts)
- [`src/cli/runtime/product-shell-attachments.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/cli/runtime/product-shell-attachments.ts)
- [`src/application/tools/peer-tool.ts`](https://github.com/tyldra-org/falryn/blob/62b00a0b6ca0b476b7e75182531d74c4aa43ec70/src/application/tools/peer-tool.ts)

Native parent: #155. Required open prerequisites: #952 for history admission, #953 for genuine resume/activation and #954 for live safe-boundary controls. Their full current scope remains unchanged. #161 consumes the resulting controls and state; it does not implement admission. #162 owns later integrated failure qualification. Ordinary unchanged-tool failures stay with #998; this issue owns peer causal-loop prevention.

## Contract, policy and state

Add a strict versioned recipient collaboration policy through the existing configuration/action owners. Absent policy means `notify-only`. Explicit user policy may select `queue-at-boundary` or `continue-once`, bind exact recipient and allowed sender generations, permitted request kinds, expiry, workspace/trust and policy revision. `queue-at-boundary` never creates an idle turn. `continue-once` may start one idle turn per admitted actionable request. Package metadata, model tool calls and received text cannot enable either mode. A general agent permission or inbound `allow` is insufficient.

Store policy and admission receipts with the existing SQLite writer and versioned migrations. The admission identity binds mailbox key/digest, recipient generation, policy revision and turn/attempt identity. Expose pending, held, denied, expired, admitted, consumed, failed and uncertain admission independently of the delivery receipt. An acknowledgement or notification cursor cannot stand in for consumed evidence. Content remains peer evidence, with bounded artifact references; it never becomes direct user input, system instructions, effect approval, a workflow edge or a child join.

Reserve the causal admission before provider execution. Persist consumption with the owning turn boundary, using the common transaction owner or a recoverable intent state if the writes span existing transactions. Test the chosen commit boundaries. A crash must reconcile recorded state before another request; never promise exactly-once external effects. An uncertain provider/tool effect remains uncertain and must not be blindly retried.

## Runtime and actual user path

Register inspect/set/reset policy and explicit continuation actions in the existing action registry. Resolve authorized sender/recipient from the live host, not model-supplied paths. Mailbox notice -> policy/generation/expiry validation -> shared bounded queue -> current turn coordinator -> #952 evidence projection -> normal provider/tool gateway -> committed result -> separately requested correlated reply. Revalidate again when dequeuing and immediately before provider dispatch.

CLI/JSON and OpenTUI actions call the same service. An ordinary one-shot CLI command cannot promise to keep a recipient alive after exit. A live shell, or later negotiated #844 host, owns the executor and cancellation. Expose availability and refusal when no executor is attached. #1058/#1059/#1060 may project the same action only when negotiated; their transports are not prerequisites for the native shell path. Extensions consume qualified existing peer actions and cannot install an alternative turn loop. #947 discovery reports actual policy and host eligibility without enabling it.

Direct user interruption takes precedence. Busy recipients queue without mutating a dispatched provider request; checkpoint/compaction and active-session changes use #954 fences. Hold, revoke, disable and endpoint retirement invalidate pending eligibility. Resume reauthenticates and revalidates policy; fork/import/replay never inherit executable pending admissions. Existing admitted work follows normal cancellation and truthful settlement.

## Bounds and failure handling

Preserve MAILBOX_LIMITS: 16-KiB text, 32-KiB envelopes, 64 pending/1-MiB queued payload, eight artifact handles/1-MiB selected bytes, 100 records/page, 64 sends/minute and existing retention/expiry bounds. Admission queues share these records rather than copying payloads. Narrow the recipient's existing task/provider budgets and deadline; never reset them for another message. Durable causal lineage retains the current maximum of eight hops. A received acknowledgement, unchanged status or a reply alone starts no automatic continuation. Further work requires a new actionable request within the same causal budget; renaming an ID cannot reset lineage. Cycles, exhausted limits or ambiguous actionability hold/refuse with an inspectable reason.

Malformed, stale, unauthorized, held, expired, full, cancelled, storage-failed, provider-unavailable and uncertain outcomes remain typed. Reading notifications or replaying receipts is effect-free. Provider backoff never permits a second competing consumer. Policy edits use expected revision; two hosts cannot admit the same key.

## Completion proof

- [ ] Two real local Falryn processes exchange a request. With policy absent, zero provider calls occur; with explicit opt-in, exactly one visible admission reaches the normal product provider path and retains peer provenance.
- [ ] Exercise idle and busy recipients, direct user input, compaction, hold/release, revoke while queued and trust/endpoint generation change. No stale content reaches a newly selected session.
- [ ] Crash after mailbox commit, admission reservation, provider dispatch and consumption commit. Restart reconciles the original identity and does not duplicate a known completed turn or uncertain effect.
- [ ] Concurrent duplicate sends, notification replay and two recovering hosts produce one admitted identity. Changed digest is refused. Test cancellation before admission and after an observed effect separately.
- [ ] A-to-B-to-A status/reply loops, exhausted budgets, expired messages and unavailable attachments stop with truthful receipts. Model policy mutation and silent copying of the next assistant response are refused.
- [ ] Source and compiled CLI/live-shell fixtures agree with model and JSON projections; #161 can display delivery versus consumption without guessing from output.

## Validation and documentation impact

Run focused owner and product-composition tests, `bun run check`, `bun run build`, and the applicable compiled smoke tests from `package.json`. Deterministic provider/transport fixtures must exercise the actual product composition, with effect counters and committed receipts; paid services are not required for correctness. Qualify each claimed native platform separately. Record unsupported combinations instead of manufacturing a pass.

`public-code-adjacent-update`: update public help, schemas/examples and CURRENT-STATE only for delivered behavior. `private-update-required`: maintainers update existing canonical owners. This public issue contains the implementation contract and requires no private access.

## Ready checklist

- [x] Current source baseline and remaining outcome are identified.
- [x] Ownership, dependencies, product wiring and failure/recovery behavior are specified.
- [x] Acceptance scenarios and documentation impact are measurable.
